// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4hgcztK4Ssg25Md8q0aVFbWocj-MJG3s',
    appId: '1:356091070795:web:493d911daf5b8f600fc0ce',
    messagingSenderId: '356091070795',
    projectId: 'habittracker-252d2',
    authDomain: 'habittracker-252d2.firebaseapp.com',
    storageBucket: 'habittracker-252d2.appspot.com',
    measurementId: 'G-LM7GV5W0HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRNhXtg2zujwSwwxSnSFg9iXCbWCIx74E',
    appId: '1:356091070795:android:b1ede24f6849a89d0fc0ce',
    messagingSenderId: '356091070795',
    projectId: 'habittracker-252d2',
    storageBucket: 'habittracker-252d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBsA2gqF7-JkBOYZcFm66fiK0S9ZeoSc',
    appId: '1:356091070795:ios:8c4611a0130eeba90fc0ce',
    messagingSenderId: '356091070795',
    projectId: 'habittracker-252d2',
    storageBucket: 'habittracker-252d2.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBsA2gqF7-JkBOYZcFm66fiK0S9ZeoSc',
    appId: '1:356091070795:ios:8c4611a0130eeba90fc0ce',
    messagingSenderId: '356091070795',
    projectId: 'habittracker-252d2',
    storageBucket: 'habittracker-252d2.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4hgcztK4Ssg25Md8q0aVFbWocj-MJG3s',
    appId: '1:356091070795:web:f797c00b2ef0094a0fc0ce',
    messagingSenderId: '356091070795',
    projectId: 'habittracker-252d2',
    authDomain: 'habittracker-252d2.firebaseapp.com',
    storageBucket: 'habittracker-252d2.appspot.com',
    measurementId: 'G-4JW3CCVJRC',
  );

}